spring:
  profiles:
    active: dev
  application:
    name: customer
  servlet:
    multipart.max-file-size: 50MB
    multipart.max-request-size: 50MB

server:
  tomcat:
    threads:
      # Tomcat 最大线程数，默认200，根据需要调整
      max: 500
      # Tomcat 最小线程数，默认10，根据需要调整
      min-spare: 10